# Generated by Django 2.0.2 on 2018-02-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMark', '0003_instagramaccount_psswrd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramAccounts',
        ),
    ]
