# Generated by Django 2.0.2 on 2018-02-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMark', '0004_delete_instagramaccounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='psswrd',
        ),
    ]
