# Generated by Django 2.0.2 on 2018-02-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMark', '0006_auto_20180219_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=1024)),
                ('locations', models.CharField(max_length=1024)),
                ('likes_hour', models.CharField(max_length=32)),
                ('comments_hour', models.CharField(max_length=32)),
                ('follows_hour', models.CharField(max_length=32)),
                ('unfollows_hour', models.CharField(max_length=32)),
                ('posted', models.CharField(max_length=32)),
                ('comments', models.CharField(max_length=32)),
            ],
        ),
    ]
