# Generated by Django 2.0.2 on 2018-02-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMark', '0011_instagramaccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='created_by',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
