# Generated by Django 2.0.2 on 2018-02-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMark', '0012_instagramaccount_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCeleryTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
