# Generated by Django 2.0.2 on 2018-02-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMark', '0013_instagramcelerytask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramcelerytask',
            old_name='id',
            new_name='account_id',
        ),
        migrations.AddField(
            model_name='instagramcelerytask',
            name='task_id',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
