# Generated by Django 2.0.2 on 2018-02-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMark', '0014_auto_20180228_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcelerytask',
            name='status',
            field=models.CharField(default='stopped', max_length=32),
            preserve_default=False,
        ),
    ]
