# Generated by Django 2.0.2 on 2018-03-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoMark', '0015_instagramcelerytask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramsettings',
            name='posted',
        ),
    ]
